### ISSUE TITLE
add funami.tech wikiless instance

### ISSUE THREAD

**Issue by ghost** [libredirect/instances#3]
instance url:
https://wikiless.funami.tech/

**Comment by ManeraKai** [comment]
I might use [Metastem](https://github.com/Metastem/wikiless)'s instances list.

**Comment by ghost** [comment]
just dont forget to only add the working ones, the dev implemented the list I made which indicates which ones are working and which ones are offline (or have a broken ui), I've just checked and it's still correct

**Comment by cameronj86** [comment]
Thanks for the list, quite a few of the libredirect's wiki instances don't allow for any of the article links to be clicked. Manually adding some instances from the metastem resolved the issue

**Edit**: This might have been because my search engine shortcut/bang was incorrectly configurated when being handed-off to libredirect  🤔
